### PR TITLE
Set and record visitors type with Adobe DTM

### PR DESCRIPTION
**Pull request by oarsi**
Perhaps @33sticks can make a short review, if i don't make any mistake.

### CODE REVIEW

**Comment by 33sticks** [comment]
There are a few spelling/grammar errors in the article but the content is phenomenal.

**Comment by oarsi** [comment]
Yeah i know my english isn't the best ;) and thx

**Comment by 33sticks** [comment]
It's all good, really appreciate your involvement with this project. I can make the edits after the article is published. Just a few minor updates.

**Comment by oarsi** [comment]
Perfect thanks.

**Comment by oarsi** [comment]
Found some Javascript structure mistakes. Will commit new after revise.

**Pull request closed without merging**
