### PR TITLE
Analytics

### PR DESCRIPTION
**Pull request by 33sticks**
Pushing adobe dtm to the responsive template

### CODE REVIEW

**Comment by oarsi** [comment]
You can just give someone acces to one property, as example with just user and none approve or publish right. There for you have to create a news group and next to default role, you can click "define role per property". If you choose user for aplaybook property and nothing for the rest, the user will just have rights for this one property.

But in generell a standalone DTM account would be perfect. If i could do something, like talking to our adobe account guys, let me know.

**Comment by 33sticks** [comment]
@oarsi interesting, maybe I haven't dug deep enough in to it as I have tried to limit access in the past but have been unsuccessful. With that said, I will give it another look, if i can provide access just to this property, I will gladly do that.

**Comment by 33sticks** [comment]
@oarsi fantastic. i just created a unique group for this project and it worked! Happy to provide you and @randyzwitch access if you let me know what email address is best to use for the account.

**Comment by oarsi** [comment]
Glad that i could help. I write you dm with my mail address.

**Pull request merged**
