### PR TITLE
Ab testing intro

### PR DESCRIPTION
**Pull request by 33sticks**

### CODE REVIEW

**Comment by randyzwitch** [comment]
Now that we're doing separate folders for each content, can you place this in the "testing" folder, then update the /layouts/.responsive.html file to add the sidebar link? The link will be `/testing/intro_to_ab_testing.html`

**Comment by 33sticks** [comment]
No problem. I made the requested changes and committed them to the ab-testing-intro branch.

**Comment by randyzwitch** [comment]
You might need to do a sync or something, see this link (no commits from today):

https://github.com/digitalanalyticscookbook/digitalanalyticscookbook.github.io/pull/13/commits

**Comment by 33sticks** [comment]
Not sure what the deal is. I committed to my master and created a separate pull request. Let me know if that is ok.

**Pull request merged**
